- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM with defaults
    azure_rm_virtualmachine:
        resource_group: awx
        name: {{ vm_name }}
        admin_username: ubuntu
        admin_password: Password123456
        image:
           offer: UbuntuServer
           publisher: Canonical
           sku: '16.04-LTS'
           version: latest
        vm_size: Standard_DS1_v2
