- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM with defaults
    azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ acc_type }}"
        storage_account: "{{ 'storage1' + vm_name }}"
        network_interfaces: "{{ 'nic1' + vm_name }}"
        admin_username: ubuntu
        admin_password: Password123456
        image:
           offer: UbuntuServer
           publisher: Canonical
           sku: '16.04-LTS'
           version: latest
